//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Drug_Table()
        {
            this.Order_Table = new HashSet<Order_Table>();
        }
    
        public int DrugID { get; set; }
        public string DrugName { get; set; }
        public string DrugDescription { get; set; }
        public Nullable<int> DrugQuantity { get; set; }
        public string Manufacturer { get; set; }
        public string UsedFor { get; set; }
        public Nullable<int> Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Table> Order_Table { get; set; }
    }
}
