//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineDirectory
    {
        public int DrugID { get; set; }
        public string DrugName { get; set; }
        public string Manufacturer { get; set; }
        public string UsedFor { get; set; }
        public string Description { get; set; }
    }
}
