//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int RecordID { get; set; }
        public int LoginID { get; set; }
        public string UserName { get; set; }
        public System.DateTime Date { get; set; }
        public string Symptoms { get; set; }
    }
}
